//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment7_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bet
    {
        public int BetID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> GameID { get; set; }
        public Nullable<System.DateTime> BetDate { get; set; }
        public string Statistic { get; set; }
        public Nullable<decimal> BetAmount { get; set; }
        public string WinOrLoss { get; set; }
        public Nullable<decimal> PayoutAmount { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User_ User_ { get; set; }
    }
}
