//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment7_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> LoungeID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
    
        public virtual PartyLounge PartyLounge { get; set; }
        public virtual User_ User_ { get; set; }
    }
}
