//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment7_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CasinoDBEntities : DbContext
    {
        public CasinoDBEntities()
            : base("name=CasinoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bet> Bets { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<PartyLounge> PartyLounges { get; set; }
        public virtual DbSet<User_> User_ { get; set; }
        public virtual DbSet<User_Type> User_Type { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
    }
}
